import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/layout/global/header";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";

const font = Poppins({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={cn(font.className, "bg-black text-white")}>
          <Header />
          <main className="px-36">{children}</main>
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
